[project]
name = "random-discogs-item"
version = "0.1.0"
dependencies = [
	"python-dotenv",     # provides `from dotenv import load_dotenv`
	"discogs-client",
	"requests-cache"
]
[project.scripts]
random-discogs-item = "random_item:main"